
#pragma config(Sensor, port1,  ,               sensorVexIQ_Color12Color)
#pragma config(Motor,  motor2,           ,             tmotorVexIQ, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{while(1)
		if(getColorName(port1)==colorRed)
	{
		setMotorTarget(motor2,180,127);
	}
	else if(getColorName(port1)==colorBlue)
	{
		setMotorTarget(motor2,0,127);
	}
	else
	{
	}
}
